import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { HeaderContainer } from "@/components/layouts/header/HeaderContainer";
import { ThemeProvider as NextThemeProvider } from "next-themes";
import { FooteerContainer } from "@/components/layouts/footer/FooteerContainer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextThemeProvider attribute="class" enableSystem defaultTheme="auto">
          <div className="flex flex-col min-h-screen">
            <HeaderContainer />
            <main className="flex-grow">{children}</main>
            <FooteerContainer />
          </div>
        </NextThemeProvider>
      </body>
    </html>
  );
}
